// setup status actions
export const FETCH_SETUP_STATUS = 'FETCH_SETUP_STATUS';
export const FETCH_SETUP_STATUS_PENDING = 'FETCH_SETUP_STATUS_PENDING';
export const FETCH_SETUP_STATUS_FULFILLED = 'FETCH_SETUP_STATUS_FULFILLED';
export const FETCH_SETUP_STATUS_REJECTED = 'FETCH_SETUP_STATUS_REJECTED';
export const UPDATE_SETUP_STATUS = 'UPDATE_SETUP_STATUS';
export const UPDATE_SETUP_STATUS_PENDING = 'UPDATE_SETUP_STATUS_PENDING';
export const UPDATE_SETUP_STATUS_FULFILLED = 'UPDATE_SETUP_STATUS_FULFILLED';
export const UPDATE_SETUP_STATUS_REJECTED = 'UPDATE_SETUP_STATUS_REJECTED';

// brackette actions
export const ADD_BRACKETTE = 'ADD_BRACKETTE';
export const ADD_BRACKETTE_PENDING = 'ADD_BRACKETTE_PENDING';
export const ADD_BRACKETTE_FULFILLED = 'ADD_BRACKETTE_FULFILLED';
export const GET_BRACKETTE = 'GET_BRACKETTE';
export const GET_BRACKETTE_PENDING = 'GET_BRACKETTE_PENDING';
export const GET_BRACKETTE_FULFILLED = 'GET_BRACKETTE_FULFILLED';
export const UPDATE_BRACKETTE = 'UPDATE_BRACKETTE';
export const UPDATE_BRACKETTE_PENDING = 'UPDATE_BRACKETTE_PENDING';
export const UPDATE_BRACKETTE_FULFILLED = 'UPDATE_BRACKETTE_FULFILLED';
export const DELETE_BRACKETTE = 'DELETE_BRACKETTE';
export const DELETE_BRACKETTE_PENDING = 'DELETE_BRACKETTE_PENDING';
export const DELETE_BRACKETTE_FULFILLED = 'DELETE_BRACKETTE_FULFILLED';
